[package]
name = "joel_os"
version = "0.1.0"
authors = ["Joel Palmer <joelpalmer@gmail.com>"]

[dependencies]
bootloader_precompiled = "0.2.0"

[package.metadata.bootimage]
default-target = "x86_64-joel_os.json"